---
title: "Javascripted Brussels Sprouts"
type: "challenge"
description: "An introduction to the basics of Javascript syntax through Brussels Sprouts recipes"
depends: "rock-paper-scissors"
visibility: "assign"
ignore:
- "evening-javascripted-brussels-sprouts.md"
